### ISSUE TITLE
Doesn't work, shows: No credentials available

### ISSUE THREAD

**Issue by laukstein** [ginkoid/yolo-demo#1]
Trying to click any https://goog-yolo.netlify.com button shows

> No credentials available

and in console

> The client origin is not permitted to use this API.

![grabilla g15788](https://user-images.githubusercontent.com/183966/47672009-99c41f80-dbb9-11e8-82a1-1ef9adc5e982.png)

**Comment by ginkoid** [comment]
Sadly, Google has restricted their YOLO one-tap functionality to approved domains. The form to request approval doesn't even work.

Until Google opens it up to all sites, the demo won't work.

This is [noted in the readme](https://github.com/ginkoid/yolo-demo/blob/cb8f9326c6be68cd639eb99dec685326f256fdb8/README.md).
